on:
  push:
    tags:
      - "v*"
name: Build and push Docker image from v* git tags

jobs:
  push-docker-images:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: brokenthorn/mfo-api
          tag_with_ref: true
          tag_with_sha: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }} # an extra guard: will only push the image when the event that kicked off the workflow was a push of a git tag
