name: Main

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Check code for errors"
        run: cargo check --release --package mfo-api

      - name: "Run unit and integration tests"
        run: cargo test --release --package mfo-api
